### ISSUE TITLE
r.logger is not a function

### ISSUE THREAD

**Issue by tutts** [tandibar/ng-rollbar#11]
Hey there,

Is anyone else getting `r.logger is not a function` when injecting `Rollbar` into a service and then invoked via `Rollbar.error("My error")` ?

```
TypeError: r.logger is not a function
    at Object.error (https://d37gvrvc0wt4s1.cloudfront.net/js/v1.7/rollbar.min.js:1:2168)
    at Object.validPickups (http://localhost:8100/app/app.js:13595:17)
    at Object.Job.post (http://localhost:8100/app/app.js:11543:15)
    at CurrentJobService.post (http://localhost:8100/app/app.js:11782:18)
    at http://localhost:8100/app/app.js:15371:27
    at processQueue (http://localhost:8100/lib/ionic/js/ionic.bundle.js:22016:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:22032:27
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23228:28)
    at Scope.$digest (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23044:31)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:23333:24) undefined
```

**Comment by tandibar** [comment]
It looks like the error is in the rollbar library. I just released the newest 1.8.0 version, perhaps you can try with this version again.
